$(document).ready(function(){
    $('.slider').slick({
        arrow:true,
        dots:true,
        adaptiveHeight:true,
        slidesToShow:3,
        slidesToScroll:1,
        speed:1000,
        centerMode:true,
        variableWight:true
    });
});